------DDL------
`
-- Crear base de datos (opcional; renombra si lo prefieres)
CREATE DATABASE PayTollApp;
GO
USE PayTollApp;
GO

-- Crear esquemas
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'USUARIO') EXEC('CREATE SCHEMA USUARIO');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'SERVICIO') EXEC('CREATE SCHEMA SERVICIO');
GO

-- =========================
-- USUARIO.USUARIOS
-- =========================
CREATE TABLE USUARIO.USUARIOS (
ID_USUARIO        INT IDENTITY(1,1) PRIMARY KEY,
CEDULA            NVARCHAR(20)  NOT NULL,
NOMBRE            NVARCHAR(100) NULL,
CORREO_ELECTRONICO NVARCHAR(255) NOT NULL,
CONTRASENA        NVARCHAR(255) NULL,
FECHA_CREACION    DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
CREATE UNIQUE INDEX UX_USUARIOS_CEDULA ON USUARIO.USUARIOS (CEDULA);
CREATE UNIQUE INDEX UX_USUARIOS_CORREO ON USUARIO.USUARIOS (CORREO_ELECTRONICO);
GO

-- =========================
-- USUARIO.SOLICITUDES
-- =========================
CREATE TABLE USUARIO.SOLICITUDES (
ID_SOLICITUD    INT IDENTITY(1,1) PRIMARY KEY,
ID_USUARIO      INT NOT NULL,
TIPO_SOLICITUD  NVARCHAR(50) NOT NULL,
DESCRIPCION     NVARCHAR(1000) NULL,
FECHA_SOLICITUD DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
ESTADO          NVARCHAR(50) NOT NULL DEFAULT N'Pendiente',
CONSTRAINT FK_SOLICITUDES_USUARIOS
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIOS(ID_USUARIO)
);
GO

-- =========================
-- USUARIO.CONTACTOS
-- =========================
CREATE TABLE USUARIO.CONTACTOS (
ID_CONTACTO   INT IDENTITY(1,1) PRIMARY KEY,
ID_USUARIO    INT NOT NULL,
NOMBRE        NVARCHAR(100) NULL,
CORREO        NVARCHAR(255) NULL,
MENSAJE       NVARCHAR(1000) NULL,
FECHA_CONTACTO DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
CONSTRAINT FK_CONTACTOS_USUARIOS
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIOS(ID_USUARIO)
);
GO

-- =========================
-- SERVICIO.CATEGORIAS_VEHICULOS
-- =========================
CREATE TABLE SERVICIO.CATEGORIAS_VEHICULOS (
ID_CATEGORIA     INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CATEGORIA NVARCHAR(100) NOT NULL,
DESCRIPCION      NVARCHAR(255) NULL,
PRECIO           DECIMAL(18,2) NOT NULL
);
GO

-- =========================
-- SERVICIO.VEHICULOS
-- =========================
CREATE TABLE SERVICIO.VEHICULOS (
ID_VEHICULO        INT IDENTITY(1,1) PRIMARY KEY,
ID_USUARIO         INT NOT NULL,
PLACA              NVARCHAR(10) NOT NULL,
CATEGORIA_VEHICULO INT NOT NULL,
CONSTRAINT FK_VEHICULOS_USUARIOS
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIOS(ID_USUARIO),
CONSTRAINT FK_VEHICULOS_CATEGORIA
FOREIGN KEY (CATEGORIA_VEHICULO) REFERENCES SERVICIO.CATEGORIAS_VEHICULOS(ID_CATEGORIA)
);
GO
CREATE UNIQUE INDEX UX_VEHICULOS_PLACA ON SERVICIO.VEHICULOS (PLACA);
GO

-- =========================
-- SERVICIO.PEAJES
-- =========================
CREATE TABLE SERVICIO.PEAJES (
ID_PEAJE     INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE       NVARCHAR(100) NULL,
CIUDAD       NVARCHAR(100) NULL,
DEPARTAMENTO NVARCHAR(100) NULL
);
GO

-- =========================
-- SERVICIO.TARJETAS
-- =========================
CREATE TABLE SERVICIO.TARJETAS (
ID_TARJETA      INT IDENTITY(1,1) PRIMARY KEY,
ID_USUARIO      INT NOT NULL,
SALDO           DECIMAL(18,2) NOT NULL DEFAULT 0,
FECHA_CREACION  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
TARJETA_NUMERO  NVARCHAR(20) NOT NULL,
ID_VEHICULO     INT NOT NULL,
CONSTRAINT FK_TARJETAS_USUARIOS
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIOS(ID_USUARIO),
CONSTRAINT FK_TARJETAS_VEHICULOS
FOREIGN KEY (ID_VEHICULO) REFERENCES SERVICIO.VEHICULOS(ID_VEHICULO)
);
GO
CREATE UNIQUE INDEX UX_TARJETAS_NUMERO ON SERVICIO.TARJETAS (TARJETA_NUMERO);
GO

-- =========================
-- SERVICIO.RECARGAS
-- =========================
CREATE TABLE SERVICIO.RECARGAS (
ID_RECARGA     INT IDENTITY(1,1) PRIMARY KEY,
ID_TARJETA     INT NOT NULL,
Monto          DECIMAL(18,2) NOT NULL,  -- nombre exacto según el modelo
FECHA_RECARGA  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
METODO_PAGO    NVARCHAR(50) NULL,
CONSTRAINT FK_RECARGAS_TARJETAS
FOREIGN KEY (ID_TARJETA) REFERENCES SERVICIO.TARJETAS(ID_TARJETA)
);
GO

-- =========================
-- SERVICIO.PAGOS
-- =========================
CREATE TABLE SERVICIO.PAGOS (
ID_PAGO      INT IDENTITY(1,1) PRIMARY KEY,
ID_USUARIO   INT NOT NULL,
ID_TARJETA   INT NOT NULL,
ID_PEAJE     INT NOT NULL,
ID_CATEGORIA INT NOT NULL,
Valor        DECIMAL(18,2) NOT NULL,  -- nombre exacto según el modelo
FECHA_PAGO   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
CONSTRAINT FK_PAGOS_USUARIOS
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIOS(ID_USUARIO),
CONSTRAINT FK_PAGOS_TARJETAS
FOREIGN KEY (ID_TARJETA) REFERENCES SERVICIO.TARJETAS(ID_TARJETA),
CONSTRAINT FK_PAGOS_PEAJES
FOREIGN KEY (ID_PEAJE) REFERENCES SERVICIO.PEAJES(ID_PEAJE),
CONSTRAINT FK_PAGOS_CATEGORIAS
FOREIGN KEY (ID_CATEGORIA) REFERENCES SERVICIO.CATEGORIAS_VEHICULOS(ID_CATEGORIA)
);
GO

-- =========================
-- SERVICIO.MOVIMIENTOS
-- =========================
CREATE TABLE SERVICIO.MOVIMIENTOS (
ID_MOVIMIENTO   INT IDENTITY(1,1) PRIMARY KEY,
ID_USUARIO      INT NOT NULL,
ID_TARJETA      INT NOT NULL,
ID_VEHICULO     INT NULL,
ID_PEAJE        INT NULL,
TipoMovimiento  NVARCHAR(50) NULL,        -- nombre exacto según el modelo
Monto           DECIMAL(18,2) NOT NULL,   -- nombre exacto según el modelo
SaldoAnterior   DECIMAL(18,2) NOT NULL,   -- nombre exacto según el modelo
SaldoNuevo      DECIMAL(18,2) NOT NULL,   -- nombre exacto según el modelo
FECHA_MOVIMIENTO DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
CONSTRAINT FK_MOV_USUARIOS  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIOS(ID_USUARIO),
CONSTRAINT FK_MOV_TARJETAS  FOREIGN KEY (ID_TARJETA)  REFERENCES SERVICIO.TARJETAS(ID_TARJETA),
CONSTRAINT FK_MOV_VEHICULOS FOREIGN KEY (ID_VEHICULO) REFERENCES SERVICIO.VEHICULOS(ID_VEHICULO),
CONSTRAINT FK_MOV_PEAJES    FOREIGN KEY (ID_PEAJE)    REFERENCES SERVICIO.PEAJES(ID_PEAJE)
);
GO
`